### ISSUE TITLE
Svg logo con parte a eliminar

### ISSUE THREAD

**Issue by SantiRodNu** [SantiRodNu/Proyecto-Integrado-1#2]
@pnsozko 

Hola!

Consulta, la imagen que dejaron del logo tiene otra parte a la izquierda que no iría. Cómo le saco eso? 

A esto me refiero:

![image](https://user-images.githubusercontent.com/102070385/161996660-19c5ead7-268d-4855-8541-323037ed3259.png)

**Comment by pnsozko** [comment]
te refieres a donde dice Flex?

**Comment by SantiRodNu** [comment]
Ya lo resolví :D , me olvidé de cerrarlo. 

Gracias!
